Update build Identifier and yml comments
browserstack/testng-browserstack pull request #84
Opened 2022-12-09 09:16 UTC by karanshah-browserstack

2022-12-12 07:25 UTC, Ankit098 submitted a review, later dismissed

2022-12-13 09:27 UTC, kamal-kaur04 requested changes

2022-12-13 09:27 UTC, kamal-kaur04 commented on browserstack.yml
> +# `buildIdentifer` is a unique id to differentiate every execution that gets appended to
```suggestion
# `buildIdentifier` is a unique id to differentiate every execution that gets appended to
```

2022-12-13 09:27 UTC, kamal-kaur04 commented on browserstack.yml
> +# buildName. Choose your buildIdentifier format from the the available expressions:
```suggestion
# buildName. Choose your buildIdentifier format from the available expressions:
```

2023-01-23 12:55 UTC, kamal-kaur04 approved these changes

2023-01-23 12:55 UTC, merged